#!/bin/sh

if [ "$1" == "config" ];then
	echo "graph_title DHCP Leases
graph_vlabel leases
graph_args -l 0
graph_category network
graph_scale no
leases.label leases"
	exit 0
fi


echo "leases.value `/bin/cat /tmp/dhcp.leases|/usr/bin/wc -l`"
