#!/bin/sh

# this is just awful.

CPUS=`/bin/grep '^processor' /proc/cpuinfo`
IINFO=`/bin/sed -e 's/ \{1,\}/ /g;s/^ //' /proc/interrupts|/bin/grep '.:'`
IDS=`echo "$IINFO"|/usr/bin/cut -d: -f1`

if [ "$1" == "config" ];then
	echo "graph_title Individual interrupts
graph_args --base 1000 -l 0;
graph_vlabel interrupts / \${graph_period}
graph_category system"
	for ID in $IDS;do
		IDL=`echo "$IINFO"|/bin/grep "^$ID:"`
		INFO=`echo "$IDL"|/usr/bin/cut -d\  -f$((3+$CPUS))-`
		if [ "$INFO" = "" ];then
			echo "i$ID.label $ID"
		else
			echo "i$ID.label $INFO"
			echo "i$ID.info Interrupt $ID, for device(s): $INFO"
		fi
		echo "i$ID.type DERIVE"
		echo "i$ID.min 0"
	done
	exit 0
fi
for ID in $IDS;do
	IDL=`echo "$IINFO"|/bin/grep "^$ID:"`
	VALS=`echo "$IDL"|/usr/bin/cut -d\  -f2-$((1+$CPUS))`
	VALUE=0
	for VAL in $VALS;do VALUE=$(($VALUE + $VAL));done
	echo "i$ID.value $VALUE"
done
