#!/bin/sh

if [ "$1" == "config" ]; then
	echo "graph_title Uptime
graph_args --base 1000 -l 0
graph_vlabel uptime in days
uptime.label uptime
uptime.draw AREA
uptime.cdef uptime,86400,/"
	exit 0
fi

echo "uptime.value `/usr/bin/awk '{print $1}' /proc/uptime`"
